### PR TITLE
Added a simple README file with Docker instructions

### PR DESCRIPTION
**Pull request by ibnesayeed**
Added a README file with basic intro and docker instruction.

### CODE REVIEW

**Comment by ibnesayeed** [comment]
@machawk1 isn't it the case that both `mementoes` and `mementos` are correct?

**Comment by machawk1** [comment]
@ibnesayeed "mementoes" is a _way_ more awkward spelling. I have yet to see this suffix in relevant literature. Additionally, [RFC 7089](https://tools.ietf.org/html/rfc7089) explicitly uses the plural without the "e".

**Comment by shawnmjones** [comment]
I do have unit tests. I am planning on adding a travis.yml to this.

**Comment by ibnesayeed** [comment]
> @shawnmjones: I do have unit tests. I am planning on adding a travis.yml to this.

Is this comment relevant to this PR?

**Comment by machawk1** [comment]
@shawnmjones I believe setting up CI should not be a barrier in merging this PR. I believe the image you supplied was simply GitHub checking for and not finding any such system, which would normally be executed when a PR is put forth.

**Pull request merged**
