### PR TITLE
Rename manifest file to uppercase for strict loading requirement

### LINKED ISSUE #79: Static assets and templates from manifest are not copied
When a docker image is built, following lines from the manifest file are not taking affect.

```
graft mementoembed/templates
graft mementoembed/static
```

### PR DESCRIPTION
**Pull request by ibnesayeed**
It looks like the name of the file must be strictly uppercase like `MANIFEST.in`. Fix #79

### CODE REVIEW

**Comment by ibnesayeed** [comment]
This issue was identified in https://github.com/oduwsdl/MementoEmbed/commit/b4834762a432a77ef5e2b31aa2f7a57ecc0edad6#commitcomment-29584263.

**Comment by shawnmjones** [comment]
The filesystem in macOS is case-aware, but not case-sensitive. That may explain why it works locally. Would that possibly affect how the Docker image is built?

**Comment by ibnesayeed** [comment]
>  That may explain why it works locally. Would that possibly affect how the Docker image is built?

I am not sure about it, because Docker in Mac essentially runs in  light-weight Linux VM, so Linux rules should apply inside. However, I don't know how much encapsulation of functionality do they have in that VM when it comes to file system.

**Comment by shawnmjones** [comment]
Well, it's something I'll have to consider in the future. Thanks for tracking this down. It would have confused me to no end because I would be looking at the filesystem going "why is this working"?  😅

**Pull request merged**
